#!/usr/bin/env php
<?php
declare(strict_types = 1);

$paths = [
    'vendor/autoload.php',
    '../autoload.php',
    __DIR__ . '/../autoload.php',
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/../../vendor/autoload.php',
    getcwd() . '/vendor/autoload.php',
    getcwd() . '/../vendor/autoload.php',
];

foreach ($paths as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

use function Innmind\InstallationMonitor\bootstrap;
use Innmind\CLI\{
    Main,
    Environment,
};
use Innmind\Socket\Address\Unix as Address;
use Innmind\Server\Control\ServerFactory;

new class extends Main {
    protected function main(Environment $env): void
    {
        $run = bootstrap()['commands'](
            bootstrap()['local_server_address'],
            ServerFactory::build()
        );
        $run($env);
    }
};
